[package]
authors = ["guillem.cordoba@gmail.com"]
edition = "2018"
name = "membrane_roles"
version = "0.0.1"

[lib]
crate-type = ["cdylib", "rlib"]
name = "membrane_roles"

[dependencies]
derive_more = "0"
serde = "1"

holo_hash = "0.0.2-alpha.1"
hdk = "0.0.100"
